pcf8574_output: 
	g++ pcf8574_output.cpp -o pcf8574_output -lwiringPi

pcf8574_input: 
	g++ pcf8574_input.cpp -o pcf8574_input -lwiringPi

.PHONY: clean

clean:
	rm -f *.o pcf8574_output pcf8574_input

